name: Qiita Sync

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  qiita_sync_check:
    name: Run qiita-sync sync
    runs-on: ubuntu-latest
    steps:
      - name: Tweet
        run: |
          pip install tweepy
          python ./code/twitter_api.py ${{ github.event.head_commit.message }}"